### ISSUE TITLE
REM mixin

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#57]
@function rem($size) {
        @return $size / 16 + 0rem;
    }

**Comment by yaddabristol** [comment]
can you grab that 16 by its variable at all?

**Comment by danimalweb** [comment]
https://css-tricks.com/snippets/css/less-mixin-for-rem-font-sizing/

**Comment by danimalweb** [comment]
Also consider setting the root size to 10px and then use 1.6rem = 16px etc.

**Comment by jonXmack** [comment]
That's what I planned to do initially but all of bootstraps default padding/margins/font-sizes are based around 16px so it would involve updating everything.

**Comment by danimalweb** [comment]
Hows this work for you?

http://codepen.io/lambdacreatives/pen/RWQGMd

```scss
@function strip-unit($num) {
  @return $num / ($num * 0 + 1);
}

@function rem($pxValue) {
  $rootValue: strip-unit($font-size-root);
  $value: strip-unit($pxValue);
  $remValue: ($value / $rootValue) + rem;
  @return $remValue; 
}
```
